In [1]:
import pandas as pd

In [2]:
df=pd.read_csv("Attrition - Attrition (1).csv")

In [3]:
df.head()

,Age,Attrition,BusinessTravel,DailyRate,Department,DistanceFromHome,Education,EducationField,EmployeeCount,EmployeeNumber,...,RelationshipSatisfaction,StandardHours,StockOptionLevel,TotalWorkingYears,TrainingTimesLastYear,WorkLifeBalance,YearsAtCompany,YearsInCurrentRole,YearsSinceLastPromotion,YearsWithCurrManager
0,41,Yes,Travel_Rarely,1102,Sales,1,2,Life Sciences,1,1,...,1,80,0,8,0,1,6,4,0,5
1,49,No,Travel_Frequently,279,Research & Development,8,1,Life Sciences,1,2,...,4,80,1,10,3,3,10,7,1,7
2,37,Yes,Travel_Rarely,1373,Research & Development,2,2,Other,1,4,...,2,80,0,7,3,3,0,0,0,0
3,33,No,Travel_Frequently,1392,Research & Development,3,4,Life Sciences,1,5,...,3,80,0,8,3,3,8,7,3,0
4,27,No,Travel_Rarely,591,Research & Development,2,1,Medical,1,7,...,4,80,1,6,3,3,2,2,2,2

In [4]:
  !pip install tensorflow

Collecting tensorflow
  Downloading tensorflow-2.20.0-cp313-cp313-win_amd64.whl.metadata (4.6 kB)
Collecting absl-py>=1.0.0 (from tensorflow)
  Downloading absl_py-2.3.1-py3-none-any.whl.metadata (3.3 kB)
Collecting astunparse>=1.6.0 (from tensorflow)
  Downloading astunparse-1.6.3-py2.py3-none-any.whl.metadata (4.4 kB)
Collecting flatbuffers>=24.3.25 (from tensorflow)
  Downloading flatbuffers-25.9.23-py2.py3-none-any.whl.metadata (875 bytes)
Collecting gast!=0.5.0,!=0.5.1,!=0.5.2,>=0.2.1 (from tensorflow)
  Downloading gast-0.6.0-py3-none-any.whl.metadata (1.3 kB)
Collecting google_pasta>=0.1.1 (from tensorflow)
  Downloading google_pasta-0.2.0-py3-none-any.whl.metadata (814 bytes)
Collecting libclang>=13.0.0 (from tensorflow)
  Downloading libclang-18.1.1-py2.py3-none-win_amd64.whl.metadata (5.3 kB)
Collecting opt_einsum>=2.3.2 (from tensorflow)
  Downloading opt_einsum-3.4.0-py3-none-any.whl.metadata (6.3 kB)
Requirement already satisfied: packaging in c:\users\shain\appdata\local\programs\python\python313\lib\site-packages (from tensorflow) (25.0)
Collecting protobuf>=5.28.0 (from tensorflow)
  Downloading protobuf-6.33.1-cp310-abi3-win_amd64.whl.metadata (593 bytes)
Requirement already satisfied: requests<3,>=2.21.0 in c:\users\shain\appdata\local\programs\python\python313\lib\site-packages (from tensorflow) (2.32.4)
Requirement already satisfied: setuptools in c:\users\shain\appdata\local\programs\python\python313\lib\site-packages (from tensorflow) (80.9.0)
Requirement already satisfied: six>=1.12.0 in c:\users\shain\appdata\local\programs\python\python313\lib\site-packages (from tensorflow) (1.17.0)
Collecting termcolor>=1.1.0 (from tensorflow)
  Downloading termcolor-3.2.0-py3-none-any.whl.metadata (6.4 kB)
Requirement already satisfied: typing_extensions>=3.6.6 in c:\users\shain\appdata\local\programs\python\python313\lib\site-packages (from tensorflow) (4.14.0)
Collecting wrapt>=1.11.0 (from tensorflow)
  Downloading wrapt-2.0.1-cp313-cp313-win_amd64.whl.metadata (9.2 kB)
Collecting grpcio<2.0,>=1.24.3 (from tensorflow)
  Downloading grpcio-1.76.0-cp313-cp313-win_amd64.whl.metadata (3.8 kB)
Collecting tensorboard~=2.20.0 (from tensorflow)
  Downloading tensorboard-2.20.0-py3-none-any.whl.metadata (1.8 kB)
Collecting keras>=3.10.0 (from tensorflow)
  Downloading keras-3.12.0-py3-none-any.whl.metadata (5.9 kB)
Requirement already satisfied: numpy>=1.26.0 in c:\users\shain\appdata\local\programs\python\python313\lib\site-packages (from tensorflow) (2.3.2)
Collecting h5py>=3.11.0 (from tensorflow)
  Downloading h5py-3.15.1-cp313-cp313-win_amd64.whl.metadata (3.1 kB)
Collecting ml_dtypes<1.0.0,>=0.5.1 (from tensorflow)
  Downloading ml_dtypes-0.5.4-cp313-cp313-win_amd64.whl.metadata (9.2 kB)
Requirement already satisfied: charset_normalizer<4,>=2 in c:\users\shain\appdata\local\programs\python\python313\lib\site-packages (from requests<3,>=2.21.0->tensorflow) (3.4.2)
Requirement already satisfied: idna<4,>=2.5 in c:\users\shain\appdata\local\programs\python\python313\lib\site-packages (from requests<3,>=2.21.0->tensorflow) (3.10)
Requirement already satisfied: urllib3<3,>=1.21.1 in c:\users\shain\appdata\local\programs\python\python313\lib\site-packages (from requests<3,>=2.21.0->tensorflow) (2.5.0)
Requirement already satisfied: certifi>=2017.4.17 in c:\users\shain\appdata\local\programs\python\python313\lib\site-packages (from requests<3,>=2.21.0->tensorflow) (2025.6.15)
Collecting markdown>=2.6.8 (from tensorboard~=2.20.0->tensorflow)
  Downloading markdown-3.10-py3-none-any.whl.metadata (5.1 kB)
Requirement already satisfied: pillow in c:\users\shain\appdata\local\programs\python\python313\lib\site-packages (from tensorboard~=2.20.0->tensorflow) (11.3.0)
Collecting tensorboard-data-server<0.8.0,>=0.7.0 (from tensorboard~=2.20.0->tensorflow)
  Downloading tensorboard_data_server-0.7.2-py3-none-any.whl.metadata (1.1 kB)
Collecting werkzeug>=1.0.1 (from tensorboard~=2.20.0->tensorflow)
  Downloading werkzeug-3.1.3-py3-none-any.whl.metadata (3.7 kB)
Collecting wheel<1.0,>=0.23.0 (from astunparse>=1.6.0->tensorflow)
  Downloading wheel-0.45.1-py3-none-any.whl.metadata (2.3 kB)
Collecting rich (from keras>=3.10.0->tensorflow)
  Downloading rich-14.2.0-py3-none-any.whl.metadata (18 kB)
Collecting namex (from keras>=3.10.0->tensorflow)
  Downloading namex-0.1.0-py3-none-any.whl.metadata (322 bytes)
Collecting optree (from keras>=3.10.0->tensorflow)
  Downloading optree-0.18.0-cp313-cp313-win_amd64.whl.metadata (35 kB)
Requirement already satisfied: MarkupSafe>=2.1.1 in c:\users\shain\appdata\local\programs\python\python313\lib\site-packages (from werkzeug>=1.0.1->tensorboard~=2.20.0->tensorflow) (3.0.2)
Collecting markdown-it-py>=2.2.0 (from rich->keras>=3.10.0->tensorflow)
  Downloading markdown_it_py-4.0.0-py3-none-any.whl.metadata (7.3 kB)
Requirement already satisfied: pygments<3.0.0,>=2.13.0 in c:\users\shain\appdata\local\programs\python\python313\lib\site-packages (from rich->keras>=3.10.0->tensorflow) (2.19.2)
Collecting mdurl~=0.1 (from markdown-it-py>=2.2.0->rich->keras>=3.10.0->tensorflow)
  Downloading mdurl-0.1.2-py3-none-any.whl.metadata (1.6 kB)
Downloading tensorflow-2.20.0-cp313-cp313-win_amd64.whl (332.0 MB)
   ---------------------------------------- 0.0/332.0 MB ? eta -:--:--
   ---------------------------------------- 1.6/332.0 MB 11.0 MB/s eta 0:00:31
    --------------------------------------- 4.7/332.0 MB 12.8 MB/s eta 0:00:26
   - -------------------------------------- 8.7/332.0 MB 14.5 MB/s eta 0:00:23
   - -------------------------------------- 14.2/332.0 MB 17.6 MB/s eta 0:00:19
   -- ------------------------------------- 20.4/332.0 MB 20.3 MB/s eta 0:00:16
   --- ------------------------------------ 28.0/332.0 MB 22.9 MB/s eta 0:00:14
   ---- ----------------------------------- 34.3/332.0 MB 24.0 MB/s eta 0:00:13
   ----- ---------------------------------- 43.5/332.0 MB 26.5 MB/s eta 0:00:11
   ------ --------------------------------- 50.6/332.0 MB 27.4 MB/s eta 0:00:11
   ------- -------------------------------- 59.0/332.0 MB 28.7 MB/s eta 0:00:10
   -------- ------------------------------- 69.2/332.0 MB 30.6 MB/s eta 0:00:09
   --------- ------------------------------ 79.2/332.0 MB 32.1 MB/s eta 0:00:08
   ---------- ----------------------------- 88.9/332.0 MB 33.3 MB/s eta 0:00:08
   ----------- ---------------------------- 98.8/332.0 MB 34.3 MB/s eta 0:00:07
   ------------ -------------------------- 107.0/332.0 MB 34.6 MB/s eta 0:00:07
   ------------- ------------------------- 115.3/332.0 MB 34.8 MB/s eta 0:00:07
   -------------- ------------------------ 124.5/332.0 MB 35.3 MB/s eta 0:00:06
   --------------- ----------------------- 130.3/332.0 MB 35.2 MB/s eta 0:00:06
   ---------------- ---------------------- 140.5/332.0 MB 35.7 MB/s eta 0:00:06
   ----------------- --------------------- 152.0/332.0 MB 36.4 MB/s eta 0:00:05
   ------------------ -------------------- 158.6/332.0 MB 36.3 MB/s eta 0:00:05
   ------------------- ------------------- 165.4/332.0 MB 35.9 MB/s eta 0:00:05
   -------------------- ------------------ 171.2/332.0 MB 35.6 MB/s eta 0:00:05
   -------------------- ------------------ 178.5/332.0 MB 35.6 MB/s eta 0:00:05
   --------------------- ----------------- 183.5/332.0 MB 35.1 MB/s eta 0:00:05
   ---------------------- ---------------- 190.6/332.0 MB 35.1 MB/s eta 0:00:05
   ---------------------- ---------------- 194.8/332.0 MB 34.5 MB/s eta 0:00:04
   ----------------------- --------------- 198.4/332.0 MB 35.0 MB/s eta 0:00:04
   ------------------------ -------------- 206.8/332.0 MB 33.9 MB/s eta 0:00:04
   ------------------------- ------------- 215.5/332.0 MB 34.2 MB/s eta 0:00:04
   ------------------------- ------------- 219.4/332.0 MB 33.8 MB/s eta 0:00:04
   -------------------------- ------------ 226.8/332.0 MB 33.8 MB/s eta 0:00:04
   --------------------------- ----------- 235.9/332.0 MB 34.0 MB/s eta 0:00:03
   ---------------------------- ---------- 241.2/332.0 MB 33.7 MB/s eta 0:00:03
   ----------------------------- --------- 249.0/332.0 MB 33.8 MB/s eta 0:00:03
   ------------------------------ -------- 257.4/332.0 MB 34.0 MB/s eta 0:00:03
   ------------------------------- ------- 266.1/332.0 MB 35.2 MB/s eta 0:00:02
   -------------------------------- ------ 275.8/332.0 MB 36.3 MB/s eta 0:00:02
   --------------------------------- ----- 281.0/332.0 MB 36.2 MB/s eta 0:00:02
   --------------------------------- ----- 287.3/332.0 MB 36.1 MB/s eta 0:00:02
   ---------------------------------- ---- 295.4/332.0 MB 36.1 MB/s eta 0:00:02
   ----------------------------------- --- 301.7/332.0 MB 35.9 MB/s eta 0:00:01
   ------------------------------------ -- 310.9/332.0 MB 36.1 MB/s eta 0:00:01
   ------------------------------------- - 318.0/332.0 MB 36.0 MB/s eta 0:00:01
   --------------------------------------  327.2/332.0 MB 35.9 MB/s eta 0:00:01
   --------------------------------------  331.9/332.0 MB 35.8 MB/s eta 0:00:01
   --------------------------------------  331.9/332.0 MB 35.8 MB/s eta 0:00:01
   --------------------------------------  331.9/332.0 MB 35.8 MB/s eta 0:00:01
   --------------------------------------  331.9/332.0 MB 35.8 MB/s eta 0:00:01
   --------------------------------------  331.9/332.0 MB 35.8 MB/s eta 0:00:01
   --------------------------------------  331.9/332.0 MB 35.8 MB/s eta 0:00:01
   --------------------------------------  331.9/332.0 MB 35.8 MB/s eta 0:00:01
   --------------------------------------  331.9/332.0 MB 35.8 MB/s eta 0:00:01
   --------------------------------------  331.9/332.0 MB 35.8 MB/s eta 0:00:01
   --------------------------------------- 332.0/332.0 MB 28.6 MB/s eta 0:00:00
Downloading grpcio-1.76.0-cp313-cp313-win_amd64.whl (4.7 MB)
   ---------------------------------------- 0.0/4.7 MB ? eta -:--:--
   ---------------------------------------- 4.7/4.7 MB 34.3 MB/s eta 0:00:00
Downloading ml_dtypes-0.5.4-cp313-cp313-win_amd64.whl (212 kB)
Downloading tensorboard-2.20.0-py3-none-any.whl (5.5 MB)
   ---------------------------------------- 0.0/5.5 MB ? eta -:--:--
   -------------------------------- ------- 4.5/5.5 MB 20.8 MB/s eta 0:00:01
   ---------------------------------------- 5.5/5.5 MB 19.9 MB/s eta 0:00:00
Downloading tensorboard_data_server-0.7.2-py3-none-any.whl (2.4 kB)
Downloading absl_py-2.3.1-py3-none-any.whl (135 kB)
Downloading astunparse-1.6.3-py2.py3-none-any.whl (12 kB)
Downloading wheel-0.45.1-py3-none-any.whl (72 kB)
Downloading flatbuffers-25.9.23-py2.py3-none-any.whl (30 kB)
Downloading gast-0.6.0-py3-none-any.whl (21 kB)
Downloading google_pasta-0.2.0-py3-none-any.whl (57 kB)
Downloading h5py-3.15.1-cp313-cp313-win_amd64.whl (2.9 MB)
   ---------------------------------------- 0.0/2.9 MB ? eta -:--:--
   ---------------------------------------- 2.9/2.9 MB 30.4 MB/s eta 0:00:00
Downloading keras-3.12.0-py3-none-any.whl (1.5 MB)
   ---------------------------------------- 0.0/1.5 MB ? eta -:--:--
   ---------------------------------------- 1.5/1.5 MB 19.6 MB/s eta 0:00:00
Downloading libclang-18.1.1-py2.py3-none-win_amd64.whl (26.4 MB)
   ---------------------------------------- 0.0/26.4 MB ? eta -:--:--
   --------------- ------------------------ 10.5/26.4 MB 52.0 MB/s eta 0:00:01
   ------------------------------- -------- 21.0/26.4 MB 50.1 MB/s eta 0:00:01
   ---------------------------------------  26.2/26.4 MB 41.5 MB/s eta 0:00:01
   ---------------------------------------- 26.4/26.4 MB 31.4 MB/s eta 0:00:00
Downloading markdown-3.10-py3-none-any.whl (107 kB)
Downloading opt_einsum-3.4.0-py3-none-any.whl (71 kB)
Downloading protobuf-6.33.1-cp310-abi3-win_amd64.whl (436 kB)
Downloading termcolor-3.2.0-py3-none-any.whl (7.7 kB)
Downloading werkzeug-3.1.3-py3-none-any.whl (224 kB)
Downloading wrapt-2.0.1-cp313-cp313-win_amd64.whl (60 kB)
Downloading namex-0.1.0-py3-none-any.whl (5.9 kB)
Downloading optree-0.18.0-cp313-cp313-win_amd64.whl (314 kB)
Downloading rich-14.2.0-py3-none-any.whl (243 kB)
Downloading markdown_it_py-4.0.0-py3-none-any.whl (87 kB)
Downloading mdurl-0.1.2-py3-none-any.whl (10.0 kB)
Installing collected packages: namex, libclang, flatbuffers, wrapt, wheel, werkzeug, termcolor, tensorboard-data-server, protobuf, optree, opt_einsum, ml_dtypes, mdurl, markdown, h5py, grpcio, google_pasta, gast, absl-py, tensorboard, markdown-it-py, astunparse, rich, keras, tensorflow

   - --------------------------------------  1/25 [libclang]
   - --------------------------------------  1/25 [libclang]
   - --------------------------------------  1/25 [libclang]
   - --------------------------------------  1/25 [libclang]
   - --------------------------------------  1/25 [libclang]
   - --------------------------------------  1/25 [libclang]
   - --------------------------------------  1/25 [libclang]
   --- ------------------------------------  2/25 [flatbuffers]
   --- ------------------------------------  2/25 [flatbuffers]
   ---- -----------------------------------  3/25 [wrapt]
   ---- -----------------------------------  3/25 [wrapt]
   ---- -----------------------------------  3/25 [wrapt]
   ------ ---------------------------------  4/25 [wheel]
   ------ ---------------------------------  4/25 [wheel]
   ------ ---------------------------------  4/25 [wheel]
   ------ ---------------------------------  4/25 [wheel]
   ------ ---------------------------------  4/25 [wheel]
   ------ ---------------------------------  4/25 [wheel]
   ------ ---------------------------------  4/25 [wheel]
   -------- -------------------------------  5/25 [werkzeug]
   -------- -------------------------------  5/25 [werkzeug]
   -------- -------------------------------  5/25 [werkzeug]
   -------- -------------------------------  5/25 [werkzeug]
   -------- -------------------------------  5/25 [werkzeug]
   -------- -------------------------------  5/25 [werkzeug]
   -------- -------------------------------  5/25 [werkzeug]
   -------- -------------------------------  5/25 [werkzeug]
   -------- -------------------------------  5/25 [werkzeug]
   -------- -------------------------------  5/25 [werkzeug]
   -------- -------------------------------  5/25 [werkzeug]
   -------- -------------------------------  5/25 [werkzeug]
   -------- -------------------------------  5/25 [werkzeug]
   --------- ------------------------------  6/25 [termcolor]
   ------------ ---------------------------  8/25 [protobuf]
   ------------ ---------------------------  8/25 [protobuf]
   ------------ ---------------------------  8/25 [protobuf]
   ------------ ---------------------------  8/25 [protobuf]
   ------------ ---------------------------  8/25 [protobuf]
   ------------ ---------------------------  8/25 [protobuf]
   ------------ ---------------------------  8/25 [protobuf]
   ------------ ---------------------------  8/25 [protobuf]
   ------------ ---------------------------  8/25 [protobuf]
   ------------ ---------------------------  8/25 [protobuf]
   ------------ ---------------------------  8/25 [protobuf]
   ------------ ---------------------------  8/25 [protobuf]
   ------------ ---------------------------  8/25 [protobuf]
   ------------ ---------------------------  8/25 [protobuf]
   ------------ ---------------------------  8/25 [protobuf]
   -------------- -------------------------  9/25 [optree]
   -------------- -------------------------  9/25 [optree]
   -------------- -------------------------  9/25 [optree]
   -------------- -------------------------  9/25 [optree]
   ---------------- ----------------------- 10/25 [opt_einsum]
   ---------------- ----------------------- 10/25 [opt_einsum]
   ---------------- ----------------------- 10/25 [opt_einsum]
   ---------------- ----------------------- 10/25 [opt_einsum]
   ---------------- ----------------------- 10/25 [opt_einsum]
   ---------------- ----------------------- 10/25 [opt_einsum]
   ----------------- ---------------------- 11/25 [ml_dtypes]
   ------------------- -------------------- 12/25 [mdurl]
   -------------------- ------------------- 13/25 [markdown]
   -------------------- ------------------- 13/25 [markdown]
   -------------------- ------------------- 13/25 [markdown]
   -------------------- ------------------- 13/25 [markdown]
   -------------------- ------------------- 13/25 [markdown]
   -------------------- ------------------- 13/25 [markdown]
   -------------------- ------------------- 13/25 [markdown]
   -------------------- ------------------- 13/25 [markdown]
   -------------------- ------------------- 13/25 [markdown]
   -------------------- ------------------- 13/25 [markdown]
   ---------------------- ----------------- 14/25 [h5py]
   ---------------------- ----------------- 14/25 [h5py]
   ---------------------- ----------------- 14/25 [h5py]
   ---------------------- ----------------- 14/25 [h5py]
   ---------------------- ----------------- 14/25 [h5py]
   ---------------------- ----------------- 14/25 [h5py]
   ---------------------- ----------------- 14/25 [h5py]
   ---------------------- ----------------- 14/25 [h5py]
   ---------------------- ----------------- 14/25 [h5py]
   ---------------------- ----------------- 14/25 [h5py]
   ---------------------- ----------------- 14/25 [h5py]
   ---------------------- ----------------- 14/25 [h5py]
   ---------------------- ----------------- 14/25 [h5py]
   ---------------------- ----------------- 14/25 [h5py]
   ---------------------- ----------------- 14/25 [h5py]
   ------------------------ --------------- 15/25 [grpcio]
   ------------------------ --------------- 15/25 [grpcio]
   ------------------------ --------------- 15/25 [grpcio]
   ------------------------ --------------- 15/25 [grpcio]
   ------------------------ --------------- 15/25 [grpcio]
   ------------------------ --------------- 15/25 [grpcio]
   ------------------------ --------------- 15/25 [grpcio]
   ------------------------ --------------- 15/25 [grpcio]
   ------------------------ --------------- 15/25 [grpcio]
   ------------------------ --------------- 15/25 [grpcio]
   ------------------------ --------------- 15/25 [grpcio]
   ------------------------- -------------- 16/25 [google_pasta]
   ------------------------- -------------- 16/25 [google_pasta]
   ------------------------- -------------- 16/25 [google_pasta]
   ------------------------- -------------- 16/25 [google_pasta]
   ------------------------- -------------- 16/25 [google_pasta]
   --------------------------- ------------ 17/25 [gast]
   --------------------------- ------------ 17/25 [gast]
   ---------------------------- ----------- 18/25 [absl-py]
   ---------------------------- ----------- 18/25 [absl-py]
   ---------------------------- ----------- 18/25 [absl-py]
   ---------------------------- ----------- 18/25 [absl-py]
   ---------------------------- ----------- 18/25 [absl-py]
   ------------------------------ --------- 19/25 [tensorboard]
   ------------------------------ --------- 19/25 [tensorboard]
   ------------------------------ --------- 19/25 [tensorboard]
   ------------------------------ --------- 19/25 [tensorboard]
   ------------------------------ --------- 19/25 [tensorboard]
   ------------------------------ --------- 19/25 [tensorboard]
   ------------------------------ --------- 19/25 [tensorboard]
   ------------------------------ --------- 19/25 [tensorboard]
   ------------------------------ --------- 19/25 [tensorboard]
   ------------------------------ --------- 19/25 [tensorboard]
   ------------------------------ --------- 19/25 [tensorboard]
   ------------------------------ --------- 19/25 [tensorboard]
   ------------------------------ --------- 19/25 [tensorboard]
   ------------------------------ --------- 19/25 [tensorboard]
   ------------------------------ --------- 19/25 [tensorboard]
   ------------------------------ --------- 19/25 [tensorboard]
   ------------------------------ --------- 19/25 [tensorboard]

[notice] A new release of pip is available: 25.1.1 -> 25.3
[notice] To update, run: python.exe -m pip install --upgrade pip

In [5]:
import numpy as np

In [7]:
import tensorflow as tf
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder, StandardScaler
from sklearn.metrics import accuracy_score

In [8]:
df.columns

Index(['Age', 'Attrition', 'BusinessTravel', 'DailyRate', 'Department',
       'DistanceFromHome', 'Education', 'EducationField', 'EmployeeCount',
       'EmployeeNumber', 'EnvironmentSatisfaction', 'Gender', 'HourlyRate',
       'JobInvolvement', 'JobLevel', 'JobRole', 'JobSatisfaction',
       'MaritalStatus', 'MonthlyIncome', 'MonthlyRate', 'NumCompaniesWorked',
       'Over18', 'OverTime', 'PercentSalaryHike', 'PerformanceRating',
       'RelationshipSatisfaction', 'StandardHours', 'StockOptionLevel',
       'TotalWorkingYears', 'TrainingTimesLastYear', 'WorkLifeBalance',
       'YearsAtCompany', 'YearsInCurrentRole', 'YearsSinceLastPromotion',
       'YearsWithCurrManager'],
      dtype='object')

In [9]:
df=df.dropna()

In [11]:
x=df.drop(columns=["Attrition"],axis=1)
y=df["Attrition"]

In [12]:
x.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1470 entries, 0 to 1469
Data columns (total 34 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   Age                       1470 non-null   int64
 1   BusinessTravel            1470 non-null   object
 2   DailyRate                 1470 non-null   int64
 3   Department                1470 non-null   object
 4   DistanceFromHome          1470 non-null   int64
 5   Education                 1470 non-null   int64
 6   EducationField            1470 non-null   object
 7   EmployeeCount             1470 non-null   int64
 8   EmployeeNumber            1470 non-null   int64
 9   EnvironmentSatisfaction   1470 non-null   int64
 10  Gender                    1470 non-null   object
 11  HourlyRate                1470 non-null   int64
 12  JobInvolvement            1470 non-null   int64
 13  JobLevel                  1470 non-null   int64
 14  JobRole                   1470 non-null   object
 15  JobSatisfaction           1470 non-null   int64
 16  MaritalStatus             1470 non-null   object
 17  MonthlyIncome             1470 non-null   int64
 18  MonthlyRate               1470 non-null   int64
 19  NumCompaniesWorked        1470 non-null   int64
 20  Over18                    1470 non-null   object
 21  OverTime                  1470 non-null   object
 22  PercentSalaryHike         1470 non-null   int64
 23  PerformanceRating         1470 non-null   int64
 24  RelationshipSatisfaction  1470 non-null   int64
 25  StandardHours             1470 non-null   int64
 26  StockOptionLevel          1470 non-null   int64
 27  TotalWorkingYears         1470 non-null   int64
 28  TrainingTimesLastYear     1470 non-null   int64
 29  WorkLifeBalance           1470 non-null   int64
 30  YearsAtCompany            1470 non-null   int64
 31  YearsInCurrentRole        1470 non-null   int64
 32  YearsSinceLastPromotion   1470 non-null   int64
 33  YearsWithCurrManager      1470 non-null   int64
dtypes: int64(26), object(8)
memory usage: 390.6+ KB

In [16]:
categorical_features=["BusinessTravel",
                     "Department",
                     "EducationField",
                     "Gender",
                     "JobRole",
                     "MaritalStatus",
                     "Over18",
                     "OverTime"]

In [17]:
x_encoded=pd.get_dummies(x,columns=categorical_features,
                        drop_first=True)

In [18]:
x_encoded=x_encoded.astype(int)

In [19]:
x_encoded

,Age,DailyRate,DistanceFromHome,Education,EmployeeCount,EmployeeNumber,EnvironmentSatisfaction,HourlyRate,JobInvolvement,JobLevel,...,JobRole_Laboratory Technician,JobRole_Manager,JobRole_Manufacturing Director,JobRole_Research Director,JobRole_Research Scientist,JobRole_Sales Executive,JobRole_Sales Representative,MaritalStatus_Married,MaritalStatus_Single,OverTime_Yes
0,41,1102,1,2,1,1,2,94,3,2,...,0,0,0,0,0,1,0,0,1,1
1,49,279,8,1,1,2,3,61,2,2,...,0,0,0,0,1,0,0,1,0,0
2,37,1373,2,2,1,4,4,92,2,1,...,1,0,0,0,0,0,0,0,1,1
3,33,1392,3,4,1,5,4,56,3,1,...,0,0,0,0,1,0,0,1,0,1
4,27,591,2,1,1,7,1,40,3,1,...,1,0,0,0,0,0,0,1,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1465,36,884,23,2,1,2061,3,41,4,2,...,1,0,0,0,0,0,0,1,0,0
1466,39,613,6,1,1,2062,4,42,2,3,...,0,0,0,0,0,0,0,1,0,0
1467,27,155,4,3,1,2064,2,87,4,2,...,0,0,1,0,0,0,0,1,0,1
1468,49,1023,2,3,1,2065,4,63,2,2,...,0,0,0,0,0,1,0,1,0,0
1469,34,628,8,3,1,2068,2,82,4,2,...,1,0,0,0,0,0,0,1,0,0

In [20]:
lb=LabelEncoder()

In [21]:
y_encoded=lb.fit_transform(y)
y_encoded

array([1, 0, 1, ..., 0, 0, 0], shape=(1470,))

In [22]:
x_train,x_test,y_train,y_test=train_test_split(x_encoded,
                                              y_encoded,
                                               test_size=0.2,
                                               random_state=42
                                              )

In [23]:
x_train.head()

,Age,DailyRate,DistanceFromHome,Education,EmployeeCount,EmployeeNumber,EnvironmentSatisfaction,HourlyRate,JobInvolvement,JobLevel,...,JobRole_Laboratory Technician,JobRole_Manager,JobRole_Manufacturing Director,JobRole_Research Director,JobRole_Research Scientist,JobRole_Sales Executive,JobRole_Sales Representative,MaritalStatus_Married,MaritalStatus_Single,OverTime_Yes
1097,24,350,21,2,1,1551,3,57,2,1,...,1,0,0,0,0,0,0,0,0,0
727,18,287,5,2,1,1012,2,73,3,1,...,0,0,0,0,1,0,0,0,1,0
254,29,1247,20,2,1,349,4,45,3,2,...,0,0,0,0,0,1,0,0,0,0
1175,39,492,12,3,1,1654,4,66,3,2,...,0,0,1,0,0,0,0,1,0,0
1341,31,311,20,3,1,1881,2,89,3,2,...,1,0,0,0,0,0,0,0,0,0

In [24]:
sc=StandardScaler()

In [25]:
x_train_scaled=sc.fit_transform(x_train)
x_test_scaled=sc.transform(x_test)

In [27]:
model=tf.keras.models.Sequential([
    tf.keras.layers.Dense(units=128, activation="relu",
                         input_dim= x_train_scaled.shape[1]), #input layer
    tf.keras.layers.Dropout(0.3),
    tf.keras.layers.Dense(units=64, activation ="relu"), #hidden layer
    tf.keras.layers.Dropout(0.3),
    tf.keras.layers.Dense(units=1,activation="sigmoid")  #eooutput layer
])

In [28]:
#Compile the model

In [29]:
loss_fn =tf.keras.losses.BinaryCrossentropy()
metrics=["accuracy"]

In [31]:
learning_rate=0.001
momentum=0.9
optimizer=tf.keras.optimizers.SGD(learning_rate-learning_rate,
                                  momentum=momentum,nesterov=True)

In [32]:
model.compile(optimizer=optimizer, loss=loss_fn,metrics=metrics)

In [33]:
#train the model

In [35]:
model.fit(x_train_scaled,
         y_train,
         epochs=50,
         batch_size=8,
         validation_split=0.1)

Epoch 1/50
133/133 ━━━━━━━━━━━━━━━━━━━━ 3s 9ms/step - accuracy: 0.6569 - loss: 0.6229 - val_accuracy: 0.6356 - val_loss: 0.6461
Epoch 2/50
133/133 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - accuracy: 0.6437 - loss: 0.6342 - val_accuracy: 0.6356 - val_loss: 0.6461
Epoch 3/50
133/133 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - accuracy: 0.6342 - loss: 0.6354 - val_accuracy: 0.6356 - val_loss: 0.6461
Epoch 4/50
133/133 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - accuracy: 0.6531 - loss: 0.6339 - val_accuracy: 0.6356 - val_loss: 0.6461
Epoch 5/50
133/133 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - accuracy: 0.6645 - loss: 0.6320 - val_accuracy: 0.6356 - val_loss: 0.6461
Epoch 6/50
133/133 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - accuracy: 0.6588 - loss: 0.6269 - val_accuracy: 0.6356 - val_loss: 0.6461
Epoch 7/50
133/133 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - accuracy: 0.6418 - loss: 0.6306 - val_accuracy: 0.6356 - val_loss: 0.6461
Epoch 8/50
133/133 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - accuracy: 0.6380 - loss: 0.6412 - val_accuracy: 0.6356 - val_loss: 0.6461
Epoch 9/50
133/133 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - accuracy: 0.6493 - loss: 0.6269 - val_accuracy: 0.6356 - val_loss: 0.6461
Epoch 10/50
133/133 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - accuracy: 0.6238 - loss: 0.6319 - val_accuracy: 0.6356 - val_loss: 0.6461
Epoch 11/50
133/133 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - accuracy: 0.6389 - loss: 0.6287 - val_accuracy: 0.6356 - val_loss: 0.6461
Epoch 12/50
133/133 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - accuracy: 0.6446 - loss: 0.6302 - val_accuracy: 0.6356 - val_loss: 0.6461
Epoch 13/50
133/133 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - accuracy: 0.6607 - loss: 0.6198 - val_accuracy: 0.6356 - val_loss: 0.6461
Epoch 14/50
133/133 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - accuracy: 0.6371 - loss: 0.6381 - val_accuracy: 0.6356 - val_loss: 0.6461
Epoch 15/50
133/133 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - accuracy: 0.6569 - loss: 0.6326 - val_accuracy: 0.6356 - val_loss: 0.6461
Epoch 16/50
133/133 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - accuracy: 0.6304 - loss: 0.6555 - val_accuracy: 0.6356 - val_loss: 0.6461
Epoch 17/50
133/133 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - accuracy: 0.6550 - loss: 0.6332 - val_accuracy: 0.6356 - val_loss: 0.6461
Epoch 18/50
133/133 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - accuracy: 0.6163 - loss: 0.6529 - val_accuracy: 0.6356 - val_loss: 0.6461
Epoch 19/50
133/133 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - accuracy: 0.6541 - loss: 0.6264 - val_accuracy: 0.6356 - val_loss: 0.6461
Epoch 20/50
133/133 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - accuracy: 0.6437 - loss: 0.6317 - val_accuracy: 0.6356 - val_loss: 0.6461
Epoch 21/50
133/133 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - accuracy: 0.6276 - loss: 0.6471 - val_accuracy: 0.6356 - val_loss: 0.6461
Epoch 22/50
133/133 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - accuracy: 0.6361 - loss: 0.6312 - val_accuracy: 0.6356 - val_loss: 0.6461
Epoch 23/50
133/133 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - accuracy: 0.6522 - loss: 0.6373 - val_accuracy: 0.6356 - val_loss: 0.6461
Epoch 24/50
133/133 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - accuracy: 0.6493 - loss: 0.6315 - val_accuracy: 0.6356 - val_loss: 0.6461
Epoch 25/50
133/133 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - accuracy: 0.6371 - loss: 0.6304 - val_accuracy: 0.6356 - val_loss: 0.6461
Epoch 26/50
133/133 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - accuracy: 0.6115 - loss: 0.6474 - val_accuracy: 0.6356 - val_loss: 0.6461
Epoch 27/50
133/133 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - accuracy: 0.6493 - loss: 0.6413 - val_accuracy: 0.6356 - val_loss: 0.6461
Epoch 28/50
133/133 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - accuracy: 0.6352 - loss: 0.6506 - val_accuracy: 0.6356 - val_loss: 0.6461
Epoch 29/50
133/133 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - accuracy: 0.6739 - loss: 0.6212 - val_accuracy: 0.6356 - val_loss: 0.6461
Epoch 30/50
133/133 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - accuracy: 0.6578 - loss: 0.6314 - val_accuracy: 0.6356 - val_loss: 0.6461
Epoch 31/50
133/133 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - accuracy: 0.6503 - loss: 0.6410 - val_accuracy: 0.6356 - val_loss: 0.6461
Epoch 32/50
133/133 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - accuracy: 0.6389 - loss: 0.6411 - val_accuracy: 0.6356 - val_loss: 0.6461
Epoch 33/50
133/133 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - accuracy: 0.6503 - loss: 0.6261 - val_accuracy: 0.6356 - val_loss: 0.6461
Epoch 34/50
133/133 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - accuracy: 0.6257 - loss: 0.6537 - val_accuracy: 0.6356 - val_loss: 0.6461
Epoch 35/50
133/133 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - accuracy: 0.6219 - loss: 0.6459 - val_accuracy: 0.6356 - val_loss: 0.6461
Epoch 36/50
133/133 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - accuracy: 0.6626 - loss: 0.6248 - val_accuracy: 0.6356 - val_loss: 0.6461
Epoch 37/50
133/133 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - accuracy: 0.6588 - loss: 0.6201 - val_accuracy: 0.6356 - val_loss: 0.6461
Epoch 38/50
133/133 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - accuracy: 0.6484 - loss: 0.6288 - val_accuracy: 0.6356 - val_loss: 0.6461
Epoch 39/50
133/133 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - accuracy: 0.6418 - loss: 0.6308 - val_accuracy: 0.6356 - val_loss: 0.6461
Epoch 40/50
133/133 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - accuracy: 0.6399 - loss: 0.6399 - val_accuracy: 0.6356 - val_loss: 0.6461
Epoch 41/50
133/133 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - accuracy: 0.6465 - loss: 0.6344 - val_accuracy: 0.6356 - val_loss: 0.6461
Epoch 42/50
133/133 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - accuracy: 0.6389 - loss: 0.6356 - val_accuracy: 0.6356 - val_loss: 0.6461
Epoch 43/50
133/133 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - accuracy: 0.6578 - loss: 0.6313 - val_accuracy: 0.6356 - val_loss: 0.6461
Epoch 44/50
133/133 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - accuracy: 0.6418 - loss: 0.6284 - val_accuracy: 0.6356 - val_loss: 0.6461
Epoch 45/50
133/133 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - accuracy: 0.6361 - loss: 0.6373 - val_accuracy: 0.6356 - val_loss: 0.6461
Epoch 46/50
133/133 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - accuracy: 0.6522 - loss: 0.6201 - val_accuracy: 0.6356 - val_loss: 0.6461
Epoch 47/50
133/133 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - accuracy: 0.6342 - loss: 0.6396 - val_accuracy: 0.6356 - val_loss: 0.6461
Epoch 48/50
133/133 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - accuracy: 0.6210 - loss: 0.6553 - val_accuracy: 0.6356 - val_loss: 0.6461
Epoch 49/50
133/133 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - accuracy: 0.6616 - loss: 0.6347 - val_accuracy: 0.6356 - val_loss: 0.6461
Epoch 50/50
133/133 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - accuracy: 0.6578 - loss: 0.6269 - val_accuracy: 0.6356 - val_loss: 0.6461

In [37]:
loss,accuracy=model.evaluate(x_test_scaled, y_test)

10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7653 - loss: 0.5833

In [38]:
print(f"test Loss ={loss: 4f}, Test Accuracy={accuracy:4f}")

test Loss = 0.583334, Test Accuracy=0.765306